name: '[CORE] 2. Develop'

on:
  workflow_call:
    inputs:
      runner:
        default: ubuntu-latest
        required: false
        type: string

jobs:
  track:
    name: Track
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Add comment to PR
        run: echo "OK"

  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout merge ref
        uses: actions/checkout@v4

      - name: Resolve API contract
        run: echo "OK"
      
      - name: Lint API contract
        run: echo "OK"

      - name: Checkout main ref
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Resolve main API contract
        run: echo "OK"
      
      - name: Diff API contracts
        run: echo "OK"
      
      - name: Create build package
        run: echo "OK"
      
      - name: Publish build package
        run: echo "OK"

  style-guide:
    name: Style Guide
    runs-on: ${{ inputs.runner }}
    needs: build
    steps:
      - name: Download build package
        run: echo "OK"
      
      - name: Validate style guide
        run: echo "OK"

  aws-dev:
    name: AWS DEV
    runs-on: ${{ inputs.runner }}
    needs: build
    steps:
      - name: Download build package
        run: echo "OK"
      
      - name: Validate AWS integrations
        run: echo "OK"
      
      - name: Validate AWS S3
        run: echo "OK"
      
      - name: Validate AWS API Gateway
        run: echo "OK"

  contract-break:
    name: Contract Break
    runs-on: ${{ inputs.runner }}
    needs: build
    continue-on-error: true
    steps:
      - name: Download build package
        run: echo "OK"
      
      - name: Validate contract break
        run: echo "OK"

  version:
    name: Version
    runs-on: ${{ inputs.runner }}
    needs: build
    continue-on-error: true
    steps:
      - name: Get current version
        run: echo "OK"
      
      - name: Calculate new version
        run: echo "OK"

  package:
    name: Package
    runs-on: ${{ inputs.runner }}
    needs:
      - style-guide
      - aws-dev
      - version
    steps:
      - name: Download build package
        run: echo "OK"
      
      - name: Create deploy package
        run: echo "OK"
      
      - name: Publish deploy package on Github
        run: echo "OK"
      
      - name: Assume AWS IAM role
        run: echo "OK"
      
      - name: Publish deploy package on AWS S3
        run: echo "OK"

  deploy:
    name: Deploy
    runs-on: ${{ inputs.runner }}
    needs: package
    steps:
      - name: Download deploy package
        run: echo "OK"
      
      - name: Deploy API contract to API Gateway
        run: echo "OK"

  pull-request:
    name: Pull Request
    runs-on: ${{ inputs.runner }}
    needs: deploy
    continue-on-error: true
    steps:
      - name: Open PR to release
        run: echo "OK"
