name: '2 - [DEV] CI & CD'

on:
  workflow_call:

jobs:
  develop:
    if: |
      startsWith(github.head_ref, 'feature') &&
      github.base_ref == 'develop' &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/core-develop.yml@main
