name: '2. Develop'

on:
  workflow_call:

jobs:
  develop:
    name: Develop
    if: |
      startsWith(github.head_ref, 'feature/') &&
      github.base_ref == 'develop' &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/core-develop.yml
