name: '3. Gates'

on:
  workflow_call:

jobs:
  pre-hom-prod:
    name: Pre HOM & PROD
    if: |
      github.head_ref == 'develop' &&
      startsWith(github.base_ref, 'release/v') &&
      github.event.pull_request.merged == false
    uses: ./.github/workflows/core-gates.yml
