name: '5. Main'

on:
  workflow_call:

jobs:
  main:
    name: Main
    if: |
      startsWith(github.head_ref, 'release/v') &&
      github.base_ref == 'main' &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/core-main.yml
