name: '5 - [PROD] Promote & Deploy'

on:
  workflow_call:

jobs:
  main:
    if: |
      startsWith(github.head_ref, 'release') &&
      github.base_ref == 'main' &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/core-main.yml@main
