name: '4. Release'

on:
  workflow_call:

jobs:
  release:
    name: Release
    if: |
      github.head_ref == 'develop' &&
      startsWith(github.base_ref, 'release/v') &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/core-release.yml
